spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:/db/changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate
